---
- hosts: all

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml

  pre_tasks:
    - name: Stop Service
      service: name=mysql state=stopped
      become: yes
      ignore_errors: yes # service may not have been installed yet

    - name: Uninstall MySQL
      apt:
        name: ['mysql-*', 'libmysql*', 'python-mysqldb']
        state: absent
        purge: yes
        autoremove: yes
      become: yes
      ignore_errors: yes # may not have installed one of the external repos yet

    - name: Uninstall MariaDB
      apt:
        name: ['mariadb-*', 'libmariadb*']
        state: absent
        purge: yes
        autoremove: yes
      become: yes
      ignore_errors: yes # may not have installed one of the external repos yet

    - name: Uninstall Percona
      apt:
        name: percona-server-*
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes # may not have installed one of the external repos yet
      become: yes

    - name: Remove MySQLdb
      shell: rm -rf /usr/local/lib/python2.7/*
      args:
        warn: no
      become: yes

    - name: Clean up APT Data
      command: apt-get clean -y
      args:
        warn: no
      become: yes

    - name: Remove MariaDB APT Repository
      apt_repository: repo="{{ item }} {{ ansible_distribution_release }} main" state=absent
      become: yes
      with_items:
        - deb {{ mariadb_apt_mirror }}/mariadb/repo/{{ mariadb_version }}/ubuntu
        - deb-src {{ mariadb_apt_mirror }}/mariadb/repo/{{ mariadb_version }}/ubuntu

    - name: Delete MySQL Data
      file: path={{ item }} state=absent
      become: yes
      with_items:
        - /var/lib/mysql
        - /etc/mysql

  tasks:
    - import_tasks: ../../tasks/main.yml

  handlers:
    - import_tasks: ../../handlers/main.yml
