---
- name: Enable Selected MySQL Version
  debconf:
    name: mysql-apt-config
    question: mysql-apt-config/select-server
    value: mysql-{{ mysql_version }}
    vtype: select
  become: yes

- name: Add MySQL Package
  apt: deb={{ mysql_deb }}
  become: yes

- name: Install MySQL
  apt: name={{ mysql_apt_packages }} state=present update_cache=yes
  become: yes
  register: mysql_installed
