---
- name: Create Database
  mysql_db:
    name:           "{{ new_db_name }}"
    login_user:     "{{ db_admin }}"
    login_password: "{{ db_pass }}"
    encoding:       utf8mb4
    collation:      utf8mb4_general_ci
    state:          present
  when: new_db_name is defined

- name: Create User
  mysql_user:
    name:            "{{ new_db_user }}"
    password:        "{{ new_db_pass }}"
    update_password: on_create
    host:            "{{ item }}"
    login_user:      "{{ db_admin }}"
    login_password:  "{{ db_pass }}"
    priv:            "{{ new_db_priv | default(new_db_name + '.*:ALL' if new_db_name is defined else '*.*:ALL,GRANT') }}"
    state:           present
    append_privs:    yes
  loop: "{{ local_hosts }}"
