source "https://rubygems.org"

gem "bundler",    ">= 2.2.10"
gem 'rake',       '~> 12.3'
gem 'rspec',      '~> 3.3'
gem 'serverspec', '~> 2.24'
gem 'net-ssh',    '~> 4.0'
gem 'docker-api', '~> 1.33'
gem 'deep_merge', '~> 1.2'
