---
- hosts: all

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  vars:
    new_db_name: test_db
    new_db_user: test_user
    new_db_pass: password123

  pre_tasks:
    - name: Get ENV
      set_fact: install_which={{ lookup('env', 'INSTALL') }}
    - name: Set Install MySQL
      set_fact: install_mysql={{ install_which == 'mysql' }}
    - name: Set Install MariaDB
      set_fact: install_mariadb={{ install_which == 'mariadb' }}
    - name: Set Install Percona
      set_fact: install_percona={{ install_which == 'percona' }}

  tasks:
    - import_tasks: tasks/main.yml

  handlers:
    - import_tasks: handlers/main.yml
