image: williamyeh/ansible:debian8

before_script:
  - apt-get update
  - apt-get install -y git
  - git submodule sync --recursive
  - git submodule update --init --recursive --remote

build1:
  stage: build
  script:
    - chmod -R a-w ../application
    # For debug:
    - ls base-bootstrap
    - ls base-bootstrap/vars
    - test -z "${SSH_PRIVATE_KEY}" && ./create_ssh_key.sh
    - test -z "${SSH_PRIVATE_KEY}" && ansible-playbook tomcat-app.yml
    - test -z "${userpassword}" && ansible-playbook tomcat-app.yml --extra-vars "ansible_ssh_pass=$userpassword ask-become-pass=$userpassword"
