---
- import_playbook: base-bootstrap/base-bootstrap.yml
- import_playbook: team-users/team-users.yml

- hosts: loadbalancer
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - geerlingguy.nginx
